<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {


        $countries = [
            array('id' => '1', 'name' => json_encode( ['ar' => 'أندورا', 'fr' => 'Andorre', 'en' => 'Andorra']), 'code' => 'ad'),
            array('id' => '2', 'name' => json_encode( ['ar' => 'الإمارات العربية المتحدة', 'fr' => 'Emirats Arabes Unis', 'en' => 'United Arab Emirates']), 'code' => 'ae'),
            array('id' => '3', 'name' => json_encode( ['ar' => 'أفغانستان', 'fr' => 'L\'Afghanistan', 'en' => 'Afghanistan']), 'code' => 'af'),
            array('id' => '4', 'name' => json_encode( ['ar' => 'أنتيغوا وبربودا', 'fr' => 'Antigua-et-Barbuda', 'en' => 'Antigua and Barbuda']), 'code' => 'ag'),
            array('id' => '5', 'name' => json_encode( ['ar' => 'أنغيلا', 'fr' => 'Anguilla', 'en' => 'Anguilla']), 'code' => 'ai'),
            array('id' => '6', 'name' => json_encode( ['ar' => 'ألبانيا', 'fr' => 'Albanie', 'en' => 'Albania']), 'code' => 'al'),
            array('id' => '7', 'name' => json_encode( ['ar' => 'أرمينيا', 'fr' => 'Arménie', 'en' => 'Armenia']), 'code' => 'am'),
            array('id' => '8', 'name' => json_encode( ['ar' => 'جزر الأنتيل الهولندية', 'fr' => 'Antilles néerlandaises', 'en' => 'Netherlands Antilles']), 'code' => 'an'),
            array('id' => '9', 'name' => json_encode( ['ar' => 'أنغولا', 'fr' => 'Angola', 'en' => 'Angola']), 'code' => 'ao'),
            array('id' => '10', 'name' => json_encode( ['ar' => 'الأرجنتين', 'fr' => 'Argentine', 'en' => 'Argentina']), 'code' => 'ar'),
            array('id' => '11', 'name' => json_encode( ['ar' => 'النمسا', 'fr' => 'L\'Autriche', 'en' => 'Austria']), 'code' => 'at'),
            array('id' => '12', 'name' => json_encode( ['ar' => 'أستراليا', 'fr' => 'Australie', 'en' => 'Australia']), 'code' => 'au'),
            array('id' => '13', 'name' => json_encode( ['ar' => 'أروبا', 'fr' => 'Aruba', 'en' => 'Aruba']), 'code' => 'aw'),
            array('id' => '14', 'name' => json_encode( ['ar' => 'أذربيجان', 'fr' => 'Azerbaïdjan', 'en' => 'Azerbaijan']), 'code' => 'az'),
            array('id' => '15', 'name' => json_encode( ['ar' => 'البوسنة والهرسك', 'fr' => 'Bosnie Herzégovine', 'en' => 'Bosnia and Herzegovina']), 'code' => 'ba'),
            array('id' => '16', 'name' => json_encode( ['ar' => 'بربادوس', 'fr' => 'La Barbade', 'en' => 'Barbados']), 'code' => 'bb'),
            array('id' => '17', 'name' => json_encode( ['ar' => 'بنغلاديش', 'fr' => 'Bangladesh', 'en' => 'Bangladesh']), 'code' => 'bd'),
            array('id' => '18', 'name' => json_encode( ['ar' => 'بلجيكا', 'fr' => 'Belgique', 'en' => 'Belgium']), 'code' => 'be'),
            array('id' => '19', 'name' => json_encode( ['ar' => 'بوركينا فاسو', 'fr' => 'Burkina Faso', 'en' => 'Burkina Faso']), 'code' => 'bf'),
            array('id' => '20', 'name' => json_encode( ['ar' => 'بلغاريا', 'fr' => 'Bulgarie', 'en' => 'Bulgaria']), 'code' => 'bg'),
            array('id' => '21', 'name' => json_encode( ['ar' => 'البحرين', 'fr' => 'Bahreïn', 'en' => 'Bahrain']), 'code' => 'bh'),
            array('id' => '22', 'name' => json_encode( ['ar' => 'بوروندي', 'fr' => 'Burundi', 'en' => 'Burundi']), 'code' => 'bi'),
            array('id' => '23', 'name' => json_encode( ['ar' => 'بنين', 'fr' => 'Bénin', 'en' => 'Benin']), 'code' => 'bj'),
            array('id' => '24', 'name' => json_encode( ['ar' => 'برمودا', 'fr' => 'Bermudes', 'en' => 'Bermuda']), 'code' => 'bm'),
            array('id' => '25', 'name' => json_encode( ['ar' => 'بروناي دار السلام', 'fr' => 'Brunei Darussalam', 'en' => 'Brunei Darussalam']), 'code' => 'bn'),
            array('id' => '26', 'name' => json_encode( ['ar' => 'بوليفيا', 'fr' => 'Bolivie', 'en' => 'Bolivia']), 'code' => 'bo'),
            array('id' => '27', 'name' => json_encode( ['ar' => 'البرازيل', 'fr' => 'Brésil', 'en' => 'Brazil']), 'code' => 'br'),
            array('id' => '28', 'name' => json_encode( ['ar' => 'الباهاما', 'fr' => 'Bahamas', 'en' => 'Bahamas']), 'code' => 'bs'),
            array('id' => '29', 'name' => json_encode( ['ar' => 'بوتان', 'fr' => 'Bhoutan', 'en' => 'Bhutan']), 'code' => 'bt'),
            array('id' => '30', 'name' => json_encode( ['ar' => 'بوتسوانا', 'fr' => 'Botswana', 'en' => 'Botswana']), 'code' => 'bw'),
            array('id' => '31', 'name' => json_encode( ['ar' => 'روسيا البيضاء', 'fr' => 'Biélorussie', 'en' => 'Belarus']), 'code' => 'by'),
            array('id' => '32', 'name' => json_encode( ['ar' => 'بليز', 'fr' => 'Belize', 'en' => 'Belize']), 'code' => 'bz'),
            array('id' => '33', 'name' => json_encode( ['ar' => 'كندا', 'fr' => 'Canada', 'en' => 'Canada']), 'code' => 'ca'),
            array('id' => '34', 'name' => json_encode( ['ar' => 'جزر كوكوس (كيلينغ)', 'fr' => 'Îles Cocos (Keeling)', 'en' => 'Cocos (Keeling) Islands']), 'code' => 'cc'),
            array('id' => '35', 'name' => json_encode( ['ar' => 'جمهورية الكونغو الديموقراطية', 'fr' => 'République Démocratique du Congo', 'en' => 'Democratic Republic of the Congo']), 'code' => 'cd'),
            array('id' => '36', 'name' => json_encode( ['ar' => 'جمهورية افريقيا الوسطى', 'fr' => 'République centrafricaine', 'en' => 'Central African Republic']), 'code' => 'cf'),
            array('id' => '37', 'name' => json_encode( ['ar' => 'الكونغو', 'fr' => 'Congo', 'en' => 'Congo']), 'code' => 'cg'),
            array('id' => '38', 'name' => json_encode( ['ar' => 'سويسرا', 'fr' => 'Suisse', 'en' => 'Switzerland']), 'code' => 'ch'),
            array('id' => '39', 'name' => json_encode( ['ar' => 'ساحل العاج (ساحل العاج)', 'fr' => 'Cote D\'Ivoire (Côte d\'Ivoire)', 'en' => 'Cote D\'Ivoire (Ivory Coast)']), 'code' => 'ci'),
            array('id' => '40', 'name' => json_encode( ['ar' => 'جزر كوك', 'fr' => 'les Îles Cook', 'en' => 'Cook Islands']), 'code' => 'ck'),
            array('id' => '41', 'name' => json_encode( ['ar' => 'تشيلي', 'fr' => 'Chili', 'en' => 'Chile']), 'code' => 'cl'),
            array('id' => '42', 'name' => json_encode( ['ar' => 'الكاميرون', 'fr' => 'Cameroun', 'en' => 'Cameroon']), 'code' => 'cm'),
            array('id' => '43', 'name' => json_encode( ['ar' => 'الصين', 'fr' => 'Chine', 'en' => 'China']), 'code' => 'cn'),
            array('id' => '44', 'name' => json_encode( ['ar' => 'كولومبيا', 'fr' => 'Colombie', 'en' => 'Colombia']), 'code' => 'co'),
            array('id' => '45', 'name' => json_encode( ['ar' => 'كوستا ريكا', 'fr' => 'Costa Rica', 'en' => 'Costa Rica']), 'code' => 'cr'),
            array('id' => '46', 'name' => json_encode( ['ar' => 'كوبا', 'fr' => 'Cuba', 'en' => 'Cuba']), 'code' => 'cu'),
            array('id' => '47', 'name' => json_encode( ['ar' => 'الرأس الأخضر', 'fr' => 'Cap-Vert', 'en' => 'Cape Verde']), 'code' => 'cv'),
            array('id' => '48', 'name' => json_encode( ['ar' => 'جزيرة الكريسماس', 'fr' => 'L\'île de noël', 'en' => 'Christmas Island']), 'code' => 'cx'),
            array('id' => '49', 'name' => json_encode( ['ar' => 'قبرص', 'fr' => 'Chypre', 'en' => 'Cyprus']), 'code' => 'cy'),
            array('id' => '50', 'name' => json_encode( ['ar' => 'جمهورية التشيك', 'fr' => 'République Tchèque', 'en' => 'Czech Republic']), 'code' => 'cz'),
            array('id' => '51', 'name' => json_encode( ['ar' => 'ألمانيا', 'fr' => 'Allemagne', 'en' => 'Germany']), 'code' => 'de'),
            array('id' => '52', 'name' => json_encode( ['ar' => 'جيبوتي', 'fr' => 'Djibouti', 'en' => 'Djibouti']), 'code' => 'dj'),
            array('id' => '53', 'name' => json_encode( ['ar' => 'الدنمارك', 'fr' => 'Danemark', 'en' => 'Denmark']), 'code' => 'dk'),
            array('id' => '54', 'name' => json_encode( ['ar' => 'دومينيكا', 'fr' => 'Dominique', 'en' => 'Dominica']), 'code' => 'dm'),
            array('id' => '55', 'name' => json_encode( ['ar' => 'جمهورية الدومنيكان', 'fr' => 'République Dominicaine', 'en' => 'Dominican Republic']), 'code' => 'do'),
            array('id' => '56', 'name' => json_encode( ['ar' => 'الجزائر', 'fr' => 'Algérie', 'en' => 'Algeria']), 'code' => 'dz'),
            array('id' => '57', 'name' => json_encode( ['ar' => 'الإكوادور', 'fr' => 'L\'Équateur', 'en' => 'Ecuador']), 'code' => 'ec'),
            array('id' => '58', 'name' => json_encode( ['ar' => 'استونيا', 'fr' => 'Estonie', 'en' => 'Estonia']), 'code' => 'ee'),
            array('id' => '59', 'name' => json_encode( ['ar' => 'مصر', 'fr' => 'Egypte', 'en' => 'Egypt']), 'code' => 'eg'),
            array('id' => '60', 'name' => json_encode( ['ar' => 'الصحراء الغربية', 'fr' => 'Sahara occidental', 'en' => 'Western Sahara']), 'code' => 'eh'),
            array('id' => '61', 'name' => json_encode( ['ar' => 'إريتريا', 'fr' => 'Erythrée', 'en' => 'Eritrea']), 'code' => 'er'),
            array('id' => '62', 'name' => json_encode( ['ar' => 'إسبانيا', 'fr' => 'Espagne', 'en' => 'Spain']), 'code' => 'es'),
            array('id' => '63', 'name' => json_encode( ['ar' => 'أثيوبيا', 'fr' => 'Ethiopie', 'en' => 'Ethiopia']), 'code' => 'et'),
            array('id' => '64', 'name' => json_encode( ['ar' => 'فنلندا', 'fr' => 'Finlande', 'en' => 'Finland']), 'code' => 'fi'),
            array('id' => '65', 'name' => json_encode( ['ar' => 'فيجي', 'fr' => 'Fidji', 'en' => 'Fiji']), 'code' => 'fj'),
            array('id' => '66', 'name' => json_encode( ['ar' => 'جزر فوكلاند (مالفيناس)', 'fr' => 'Iles Malouines (Malouines)', 'en' => 'Falkland Islands (Malvinas)']), 'code' => 'fk'),
            array('id' => '67', 'name' => json_encode( ['ar' => 'ولايات ميكرونيزيا الموحدة', 'fr' => 'États fédérés de Micronésie', 'en' => 'Federated States of Micronesia']), 'code' => 'fm'),
            array('id' => '68', 'name' => json_encode( ['ar' => 'جزر صناعية', 'fr' => 'Îles Féroé', 'en' => 'Faroe Islands']), 'code' => 'fo'),
            array('id' => '69', 'name' => json_encode( ['ar' => 'فرنسا', 'fr' => 'France', 'en' => 'France']), 'code' => 'fr'),
            array('id' => '70', 'name' => json_encode( ['ar' => 'الغابون', 'fr' => 'Gabon', 'en' => 'Gabon']), 'code' => 'ga'),
            array('id' => '71', 'name' => json_encode( ['ar' => 'بريطانيا العظمى (المملكة المتحدة)', 'fr' => 'Grande-Bretagne (UK)', 'en' => 'Great Britain (UK)']), 'code' => 'gb'),
            array('id' => '72', 'name' => json_encode( ['ar' => 'غرينادا', 'fr' => 'Grenade', 'en' => 'Grenada']), 'code' => 'gd'),
            array('id' => '73', 'name' => json_encode( ['ar' => 'جورجيا', 'fr' => 'Géorgie', 'en' => 'Georgia']), 'code' => 'ge'),
            array('id' => '74', 'name' => json_encode( ['ar' => 'غيانا الفرنسية', 'fr' => 'Guinée Française', 'en' => 'French Guiana']), 'code' => 'gf'),
            array('id' => '75', 'name' => json_encode( ['ar' => 'لا شيء', 'fr' => 'NUL', 'en' => 'NULL']), 'code' => 'gg'),
            array('id' => '76', 'name' => json_encode( ['ar' => 'غانا', 'fr' => 'Ghana', 'en' => 'Ghana']), 'code' => 'gh'),
            array('id' => '77', 'name' => json_encode( ['ar' => 'جبل طارق', 'fr' => 'Gibraltar', 'en' => 'Gibraltar']), 'code' => 'gi'),
            array('id' => '78', 'name' => json_encode( ['ar' => 'الأرض الخضراء', 'fr' => 'Groenland', 'en' => 'Greenland']), 'code' => 'gl'),
            array('id' => '79', 'name' => json_encode( ['ar' => 'غامبيا', 'fr' => 'Gambie', 'en' => 'Gambia']), 'code' => 'gm'),
            array('id' => '80', 'name' => json_encode( ['ar' => 'غينيا', 'fr' => 'Guinée', 'en' => 'Guinea']), 'code' => 'gn'),
            array('id' => '81', 'name' => json_encode( ['ar' => 'جوادلوب', 'fr' => 'La guadeloupe', 'en' => 'Guadeloupe']), 'code' => 'gp'),
            array('id' => '82', 'name' => json_encode( ['ar' => 'غينيا الإستوائية', 'fr' => 'Guinée Équatoriale', 'en' => 'Equatorial Guinea']), 'code' => 'gq'),
            array('id' => '83', 'name' => json_encode( ['ar' => 'اليونان', 'fr' => 'Grèce', 'en' => 'Greece']), 'code' => 'gr'),
            array('id' => '84', 'name' => json_encode( ['ar' => 'جورجيا وجزر ساندويتش', 'fr' => 'Géorgie du Sud et les îles Sandwich du Sud', 'en' => 'S. Georgia and S. Sandwich Islands']), 'code' => 'gs'),
            array('id' => '85', 'name' => json_encode( ['ar' => 'غواتيمالا', 'fr' => 'Guatemala', 'en' => 'Guatemala']), 'code' => 'gt'),
            array('id' => '86', 'name' => json_encode( ['ar' => 'غينيا بيساو', 'fr' => 'Guinée-Bissau', 'en' => 'Guinea-Bissau']), 'code' => 'gw'),
            array('id' => '87', 'name' => json_encode( ['ar' => 'غيانا', 'fr' => 'Guyane', 'en' => 'Guyana']), 'code' => 'gy'),
            array('id' => '88', 'name' => json_encode( ['ar' => 'هونغ كونغ', 'fr' => 'Hong Kong', 'en' => 'Hong Kong']), 'code' => 'hk'),
            array('id' => '89', 'name' => json_encode( ['ar' => 'هندوراس', 'fr' => 'Honduras', 'en' => 'Honduras']), 'code' => 'hn'),
            array('id' => '90', 'name' => json_encode( ['ar' => 'كرواتيا (هرفاتسكا)', 'fr' => 'Croatie (Hrvatska)', 'en' => 'Croatia (Hrvatska)']), 'code' => 'hr'),
            array('id' => '91', 'name' => json_encode( ['ar' => 'هايتي', 'fr' => 'Haïti', 'en' => 'Haiti']), 'code' => 'ht'),
            array('id' => '92', 'name' => json_encode( ['ar' => 'اليونان', 'fr' => 'Hongrie', 'en' => 'Hungary']), 'code' => 'hu'),
            array('id' => '93', 'name' => json_encode( ['ar' => 'أندونيسيا', 'fr' => 'Indonésie', 'en' => 'Indonesia']), 'code' => 'id'),
            array('id' => '94', 'name' => json_encode( ['ar' => 'أيرلندا', 'fr' => 'Irlande', 'en' => 'Ireland']), 'code' => 'ie'),
            array('id' => '96', 'name' => json_encode( ['ar' => 'الهند', 'fr' => 'Inde', 'en' => 'India']), 'code' => 'in'),
            array('id' => '97', 'name' => json_encode( ['ar' => 'العراق', 'fr' => 'Irak', 'en' => 'Iraq']), 'code' => 'iq'),
            array('id' => '98', 'name' => json_encode( ['ar' => 'إيران', 'fr' => 'Iran', 'en' => 'Iran']), 'code' => 'ir'),
            array('id' => '99', 'name' => json_encode( ['ar' => 'أيسلندا', 'fr' => 'Islande', 'en' => 'Iceland']), 'code' => 'is'),
            array('id' => '100', 'name' => json_encode( ['ar' => 'إيطاليا', 'fr' => 'Italie', 'en' => 'Italy']), 'code' => 'it'),
            array('id' => '101', 'name' => json_encode( ['ar' => 'جامايكا', 'fr' => 'Jamaïque', 'en' => 'Jamaica']), 'code' => 'jm'),
            array('id' => '102', 'name' => json_encode( ['ar' => 'الأردن', 'fr' => 'Jordan', 'en' => 'Jordan']), 'code' => 'jo'),
            array('id' => '103', 'name' => json_encode( ['ar' => 'اليابان', 'fr' => 'Japon', 'en' => 'Japan']), 'code' => 'jp'),
            array('id' => '104', 'name' => json_encode( ['ar' => 'كينيا', 'fr' => 'Kenya', 'en' => 'Kenya']), 'code' => 'ke'),
            array('id' => '105', 'name' => json_encode( ['ar' => 'قرغيزستان', 'fr' => 'Kirghizistan', 'en' => 'Kyrgyzstan']), 'code' => 'kg'),
            array('id' => '106', 'name' => json_encode( ['ar' => 'كمبوديا', 'fr' => 'Cambodge', 'en' => 'Cambodia']), 'code' => 'kh'),
            array('id' => '107', 'name' => json_encode( ['ar' => 'كيريباس', 'fr' => 'Kiribati', 'en' => 'Kiribati']), 'code' => 'ki'),
            array('id' => '108', 'name' => json_encode( ['ar' => 'جزر القمر', 'fr' => 'Comores', 'en' => 'Comoros']), 'code' => 'km'),
            array('id' => '109', 'name' => json_encode( ['ar' => 'سانت كيتس ونيفيس', 'fr' => 'Saint-Christophe-et-Niévès', 'en' => 'Saint Kitts and Nevis']), 'code' => 'kn'),
            array('id' => '110', 'name' => json_encode( ['ar' => 'كوريا الشمالية', 'fr' => 'Corée du Nord', 'en' => 'Korea (North)']), 'code' => 'kp'),
            array('id' => '111', 'name' => json_encode( ['ar' => 'كوريا، جنوب)', 'fr' => 'COREE DU SUD)', 'en' => 'Korea (South)']), 'code' => 'kr'),
            array('id' => '112', 'name' => json_encode( ['ar' => 'الكويت', 'fr' => 'Koweit', 'en' => 'Kuwait']), 'code' => 'kw'),
            array('id' => '113', 'name' => json_encode( ['ar' => 'جزر كايمان', 'fr' => 'Îles Caïmans', 'en' => 'Cayman Islands']), 'code' => 'ky'),
            array('id' => '114', 'name' => json_encode( ['ar' => 'كازاخستان', 'fr' => 'Le kazakhstan', 'en' => 'Kazakhstan']), 'code' => 'kz'),
            array('id' => '115', 'name' => json_encode( ['ar' => 'لاوس', 'fr' => 'Laos', 'en' => 'Laos']), 'code' => 'la'),
            array('id' => '116', 'name' => json_encode( ['ar' => 'لبنان', 'fr' => 'Liban', 'en' => 'Lebanon']), 'code' => 'lb'),
            array('id' => '117', 'name' => json_encode( ['ar' => 'القديسة لوسيا', 'fr' => 'Sainte-Lucie', 'en' => 'Saint Lucia']), 'code' => 'lc'),
            array('id' => '118', 'name' => json_encode( ['ar' => 'ليختنشتاين', 'fr' => 'Le Liechtenstein', 'en' => 'Liechtenstein']), 'code' => 'li'),
            array('id' => '119', 'name' => json_encode( ['ar' => 'سيريلانكا', 'fr' => 'Sri Lanka', 'en' => 'Sri Lanka']), 'code' => 'lk'),
            array('id' => '120', 'name' => json_encode( ['ar' => 'ليبيريا', 'fr' => 'Libéria', 'en' => 'Liberia']), 'code' => 'lr'),
            array('id' => '121', 'name' => json_encode( ['ar' => 'ليسوتو', 'fr' => 'Lesotho', 'en' => 'Lesotho']), 'code' => 'ls'),
            array('id' => '122', 'name' => json_encode( ['ar' => 'ليتوانيا', 'fr' => 'Lituanie', 'en' => 'Lithuania']), 'code' => 'lt'),
            array('id' => '123', 'name' => json_encode( ['ar' => 'لوكسمبورغ', 'fr' => 'Luxembourg', 'en' => 'Luxembourg']), 'code' => 'lu'),
            array('id' => '124', 'name' => json_encode( ['ar' => 'لاتفيا', 'fr' => 'Lettonie', 'en' => 'Latvia']), 'code' => 'lv'),
            array('id' => '125', 'name' => json_encode( ['ar' => 'ليبيا', 'fr' => 'Libye', 'en' => 'Libya']), 'code' => 'ly'),
            array('id' => '126', 'name' => json_encode( ['ar' => 'المغرب', 'fr' => 'Maroc', 'en' => 'Morocco']), 'code' => 'ma'),
            array('id' => '127', 'name' => json_encode( ['ar' => 'موناكو', 'fr' => 'Monaco', 'en' => 'Monaco']), 'code' => 'mc'),
            array('id' => '128', 'name' => json_encode( ['ar' => 'مولدوفا', 'fr' => 'La Moldavie', 'en' => 'Moldova']), 'code' => 'md'),
            array('id' => '129', 'name' => json_encode( ['ar' => 'مدغشقر', 'fr' => 'Madagascar', 'en' => 'Madagascar']), 'code' => 'mg'),
            array('id' => '130', 'name' => json_encode( ['ar' => 'جزر مارشال', 'fr' => 'Iles Marshall', 'en' => 'Marshall Islands']), 'code' => 'mh'),
            array('id' => '131', 'name' => json_encode( ['ar' => 'مقدونيا', 'fr' => 'Macédoine', 'en' => 'Macedonia']), 'code' => 'mk'),
            array('id' => '132', 'name' => json_encode( ['ar' => 'مالي', 'fr' => 'Mali', 'en' => 'Mali']), 'code' => 'ml'),
            array('id' => '133', 'name' => json_encode( ['ar' => 'ميانمار', 'fr' => 'Myanmar', 'en' => 'Myanmar']), 'code' => 'mm'),
            array('id' => '134', 'name' => json_encode( ['ar' => 'منغوليا', 'fr' => 'Mongolie', 'en' => 'Mongolia']), 'code' => 'mn'),
            array('id' => '135', 'name' => json_encode( ['ar' => 'ماكاو', 'fr' => 'Macao', 'en' => 'Macao']), 'code' => 'mo'),
            array('id' => '136', 'name' => json_encode( ['ar' => 'جزر مريانا الشمالية', 'fr' => 'Îles Mariannes du Nord', 'en' => 'Northern Mariana Islands']), 'code' => 'mp'),
            array('id' => '137', 'name' => json_encode( ['ar' => 'مارتينيك', 'fr' => 'Martinique', 'en' => 'Martinique']), 'code' => 'mq'),
            array('id' => '138', 'name' => json_encode( ['ar' => 'موريتانيا', 'fr' => 'Mauritanie', 'en' => 'Mauritania']), 'code' => 'mr'),
            array('id' => '139', 'name' => json_encode( ['ar' => 'مونتسيرات', 'fr' => 'Montserrat', 'en' => 'Montserrat']), 'code' => 'ms'),
            array('id' => '140', 'name' => json_encode( ['ar' => 'مالطا', 'fr' => 'Malte', 'en' => 'Malta']), 'code' => 'mt'),
            array('id' => '141', 'name' => json_encode( ['ar' => 'موريشيوس', 'fr' => 'Maurice', 'en' => 'Mauritius']), 'code' => 'mu'),
            array('id' => '142', 'name' => json_encode( ['ar' => 'جزر المالديف', 'fr' => 'Maldives', 'en' => 'Maldives']), 'code' => 'mv'),
            array('id' => '143', 'name' => json_encode( ['ar' => 'مالاوي', 'fr' => 'Malawi', 'en' => 'Malawi']), 'code' => 'mw'),
            array('id' => '144', 'name' => json_encode( ['ar' => 'المكسيك', 'fr' => 'Mexique', 'en' => 'Mexico']), 'code' => 'mx'),
            array('id' => '145', 'name' => json_encode( ['ar' => 'ماليزيا', 'fr' => 'Malaisie', 'en' => 'Malaysia']), 'code' => 'my'),
            array('id' => '146', 'name' => json_encode( ['ar' => 'موزمبيق', 'fr' => 'Mozambique', 'en' => 'Mozambique']), 'code' => 'mz'),
            array('id' => '147', 'name' => json_encode( ['ar' => 'ناميبيا', 'fr' => 'Namibie', 'en' => 'Namibia']), 'code' => 'na'),
            array('id' => '148', 'name' => json_encode( ['ar' => 'كاليدونيا الجديدة', 'fr' => 'Nouvelle Calédonie', 'en' => 'New Caledonia']), 'code' => 'nc'),
            array('id' => '149', 'name' => json_encode( ['ar' => 'النيجر', 'fr' => 'Niger', 'en' => 'Niger']), 'code' => 'ne'),
            array('id' => '150', 'name' => json_encode( ['ar' => 'جزيرة نورفولك', 'fr' => 'l\'ile de Norfolk', 'en' => 'Norfolk Island']), 'code' => 'nf'),
            array('id' => '151', 'name' => json_encode( ['ar' => 'نيجيريا', 'fr' => 'Nigeria', 'en' => 'Nigeria']), 'code' => 'ng'),
            array('id' => '152', 'name' => json_encode( ['ar' => 'نيكاراغوا', 'fr' => 'Nicaragua', 'en' => 'Nicaragua']), 'code' => 'ni'),
            array('id' => '153', 'name' => json_encode( ['ar' => 'هولندا', 'fr' => 'Pays-Bas', 'en' => 'Netherlands']), 'code' => 'nl'),
            array('id' => '154', 'name' => json_encode( ['ar' => 'النرويج', 'fr' => 'Norvège', 'en' => 'Norway']), 'code' => 'no'),
            array('id' => '155', 'name' => json_encode( ['ar' => 'نيبال', 'fr' => 'Népal', 'en' => 'Nepal']), 'code' => 'np'),
            array('id' => '156', 'name' => json_encode( ['ar' => 'ناورو', 'fr' => 'Nauru', 'en' => 'Nauru']), 'code' => 'nr'),
            array('id' => '157', 'name' => json_encode( ['ar' => 'نيوي', 'fr' => 'Niue', 'en' => 'Niue']), 'code' => 'nu'),
            array('id' => '158', 'name' => json_encode( ['ar' => 'نيوزيلندا (اوتياروا)', 'fr' => 'Nouvelle-Zélande (Aotearoa)', 'en' => 'New Zealand (Aotearoa)']), 'code' => 'nz'),
            array('id' => '159', 'name' => json_encode( ['ar' => 'سلطنة عمان', 'fr' => 'Oman', 'en' => 'Oman']), 'code' => 'om'),
            array('id' => '160', 'name' => json_encode( ['ar' => 'بناما', 'fr' => 'Panama', 'en' => 'Panama']), 'code' => 'pa'),
            array('id' => '161', 'name' => json_encode( ['ar' => 'بيرو', 'fr' => 'Pérou', 'en' => 'Peru']), 'code' => 'pe'),
            array('id' => '162', 'name' => json_encode( ['ar' => 'بولينيزيا الفرنسية', 'fr' => 'Polynésie française', 'en' => 'French Polynesia']), 'code' => 'pf'),
            array('id' => '163', 'name' => json_encode( ['ar' => 'بابوا غينيا الجديدة', 'fr' => 'Papouasie Nouvelle Guinée', 'en' => 'Papua New Guinea']), 'code' => 'pg'),
            array('id' => '164', 'name' => json_encode( ['ar' => 'الفلبين', 'fr' => 'Philippines', 'en' => 'Philippines']), 'code' => 'ph'),
            array('id' => '165', 'name' => json_encode( ['ar' => 'باكستان', 'fr' => 'Pakistan', 'en' => 'Pakistan']), 'code' => 'pk'),
            array('id' => '166', 'name' => json_encode( ['ar' => 'بولندا', 'fr' => 'Pologne', 'en' => 'Poland']), 'code' => 'pl'),
            array('id' => '167', 'name' => json_encode( ['ar' => 'سانت بيير وميكلون', 'fr' => 'Saint Pierre et Miquelon', 'en' => 'Saint Pierre and Miquelon']), 'code' => 'pm'),
            array('id' => '168', 'name' => json_encode( ['ar' => 'بيتكيرن', 'fr' => 'Pitcairn', 'en' => 'Pitcairn']), 'code' => 'pn'),
            array('id' => '169', 'name' => json_encode( ['ar' => 'الأراضي الفلسطينية', 'fr' => 'Territoire Palestinien', 'en' => 'Palestinian Territory']), 'code' => 'ps'),
            array('id' => '170', 'name' => json_encode( ['ar' => 'البرتغال', 'fr' => 'le Portugal', 'en' => 'Portugal']), 'code' => 'pt'),
            array('id' => '171', 'name' => json_encode( ['ar' => 'بالاو', 'fr' => 'Palau', 'en' => 'Palau']), 'code' => 'pw'),
            array('id' => '172', 'name' => json_encode( ['ar' => 'باراغواي', 'fr' => 'Paraguay', 'en' => 'Paraguay']), 'code' => 'py'),
            array('id' => '173', 'name' => json_encode( ['ar' => 'دولة قطر', 'fr' => 'Qatar', 'en' => 'Qatar']), 'code' => 'qa'),
            array('id' => '174', 'name' => json_encode( ['ar' => 'جمع شمل', 'fr' => 'Réunion', 'en' => 'Reunion']), 'code' => 're'),
            array('id' => '175', 'name' => json_encode( ['ar' => 'رومانيا', 'fr' => 'Roumanie', 'en' => 'Romania']), 'code' => 'ro'),
            array('id' => '176', 'name' => json_encode( ['ar' => 'الاتحاد الروسي', 'fr' => 'Fédération Russe', 'en' => 'Russian Federation']), 'code' => 'ru'),
            array('id' => '177', 'name' => json_encode( ['ar' => 'رواندا', 'fr' => 'Rwanda', 'en' => 'Rwanda']), 'code' => 'rw'),
            array('id' => '178', 'name' => json_encode( ['ar' => 'المملكة العربية السعودية', 'fr' => 'Arabie Saoudite', 'en' => 'Saudi Arabia']), 'code' => 'sa'),
            array('id' => '179', 'name' => json_encode( ['ar' => 'جزر سليمان', 'fr' => 'Les îles Salomon', 'en' => 'Solomon Islands']), 'code' => 'sb'),
            array('id' => '180', 'name' => json_encode( ['ar' => 'سيشيل', 'fr' => 'les Seychelles', 'en' => 'Seychelles']), 'code' => 'sc'),
            array('id' => '181', 'name' => json_encode( ['ar' => 'سودان', 'fr' => 'Soudan', 'en' => 'Sudan']), 'code' => 'sd'),
            array('id' => '182', 'name' => json_encode( ['ar' => 'السويد', 'fr' => 'Suède', 'en' => 'Sweden']), 'code' => 'se'),
            array('id' => '183', 'name' => json_encode( ['ar' => 'سنغافورة', 'fr' => 'Singapour', 'en' => 'Singapore']), 'code' => 'sg'),
            array('id' => '184', 'name' => json_encode( ['ar' => 'سانت هيلانة', 'fr' => 'Sainte Hélène', 'en' => 'Saint Helena']), 'code' => 'sh'),
            array('id' => '185', 'name' => json_encode( ['ar' => 'سلوفينيا', 'fr' => 'La slovénie', 'en' => 'Slovenia']), 'code' => 'si'),
            array('id' => '186', 'name' => json_encode( ['ar' => 'سفالبارد وجان مايان', 'fr' => 'Svalbard et Jan Mayen', 'en' => 'Svalbard and Jan Mayen']), 'code' => 'sj'),
            array('id' => '187', 'name' => json_encode( ['ar' => 'سلوفاكيا', 'fr' => 'La slovaquie', 'en' => 'Slovakia']), 'code' => 'sk'),
            array('id' => '188', 'name' => json_encode( ['ar' => 'سيرا ليون', 'fr' => 'Sierra Leone', 'en' => 'Sierra Leone']), 'code' => 'sl'),
            array('id' => '189', 'name' => json_encode( ['ar' => 'سان مارينو', 'fr' => 'Saint Marin', 'en' => 'San Marino']), 'code' => 'sm'),
            array('id' => '190', 'name' => json_encode( ['ar' => 'السنغال', 'fr' => 'Sénégal', 'en' => 'Senegal']), 'code' => 'sn'),
            array('id' => '191', 'name' => json_encode( ['ar' => 'الصومال', 'fr' => 'Somalie', 'en' => 'Somalia']), 'code' => 'so'),
            array('id' => '192', 'name' => json_encode( ['ar' => 'سورينام', 'fr' => 'Suriname', 'en' => 'Suriname']), 'code' => 'sr'),
            array('id' => '193', 'name' => json_encode( ['ar' => 'ساو تومي وبرنسيبي', 'fr' => 'Sao Tomé et Principe', 'en' => 'Sao Tome and Principe']), 'code' => 'st'),
            array('id' => '194', 'name' => json_encode( ['ar' => 'السلفادور', 'fr' => 'Le Salvador', 'en' => 'El Salvador']), 'code' => 'sv'),
            array('id' => '195', 'name' => json_encode( ['ar' => 'سوريا', 'fr' => 'Syrie', 'en' => 'Syria']), 'code' => 'sy'),
            array('id' => '196', 'name' => json_encode( ['ar' => 'سوازيلاند', 'fr' => 'Swaziland', 'en' => 'Swaziland']), 'code' => 'sz'),
            array('id' => '197', 'name' => json_encode( ['ar' => 'جزر تركس وكايكوس', 'fr' => 'îles Turques-et-Caïques', 'en' => 'Turks and Caicos Islands']), 'code' => 'tc'),
            array('id' => '198', 'name' => json_encode( ['ar' => 'تشاد', 'fr' => 'Le tchad', 'en' => 'Chad']), 'code' => 'td'),
            array('id' => '199', 'name' => json_encode( ['ar' => 'المناطق الجنوبية لفرنسا', 'fr' => 'Terres australes françaises', 'en' => 'French Southern Territories']), 'code' => 'tf'),
            array('id' => '200', 'name' => json_encode( ['ar' => 'ليذهب', 'fr' => 'Aller', 'en' => 'Togo']), 'code' => 'tg'),
            array('id' => '201', 'name' => json_encode( ['ar' => 'تايلاند', 'fr' => 'Thaïlande', 'en' => 'Thailand']), 'code' => 'th'),
            array('id' => '202', 'name' => json_encode( ['ar' => 'طاجيكستان', 'fr' => 'Tadjikistan', 'en' => 'Tajikistan']), 'code' => 'tj'),
            array('id' => '203', 'name' => json_encode( ['ar' => 'توكيلاو', 'fr' => 'Tokelau', 'en' => 'Tokelau']), 'code' => 'tk'),
            array('id' => '204', 'name' => json_encode( ['ar' => 'تركمانستان', 'fr' => 'Turkménistan', 'en' => 'Turkmenistan']), 'code' => 'tm'),
            array('id' => '205', 'name' => json_encode( ['ar' => 'تونس', 'fr' => 'Tunisie', 'en' => 'Tunisia']), 'code' => 'tn'),
            array('id' => '206', 'name' => json_encode( ['ar' => 'تونغا', 'fr' => 'Tonga', 'en' => 'Tonga']), 'code' => 'to'),
            array('id' => '207', 'name' => json_encode( ['ar' => 'ديك رومي', 'fr' => 'dinde', 'en' => 'Turkey']), 'code' => 'tr'),
            array('id' => '208', 'name' => json_encode( ['ar' => 'ترينداد وتوباغو', 'fr' => 'Trinité-et-Tobago', 'en' => 'Trinidad and Tobago']), 'code' => 'tt'),
            array('id' => '209', 'name' => json_encode( ['ar' => 'توفالو', 'fr' => 'Tuvalu', 'en' => 'Tuvalu']), 'code' => 'tv'),
            array('id' => '210', 'name' => json_encode( ['ar' => 'تايوان', 'fr' => 'Taïwan', 'en' => 'Taiwan']), 'code' => 'tw'),
            array('id' => '211', 'name' => json_encode( ['ar' => 'تنزانيا', 'fr' => 'Tanzanie', 'en' => 'Tanzania']), 'code' => 'tz'),
            array('id' => '212', 'name' => json_encode( ['ar' => 'أوكرانيا', 'fr' => 'Ukraine', 'en' => 'Ukraine']), 'code' => 'ua'),
            array('id' => '213', 'name' => json_encode( ['ar' => 'أوغندا', 'fr' => 'Ouganda', 'en' => 'Uganda']), 'code' => 'ug'),
            array('id' => '214', 'name' => json_encode( ['ar' => 'أوروغواي', 'fr' => 'Uruguay', 'en' => 'Uruguay']), 'code' => 'uy'),
            array('id' => '215', 'name' => json_encode( ['ar' => 'أوزبكستان', 'fr' => 'Ouzbékistan', 'en' => 'Uzbekistan']), 'code' => 'uz'),
            array('id' => '216', 'name' => json_encode( ['ar' => 'سانت فنسنت وجزر غرينادين', 'fr' => 'Saint-Vincent-et-les-Grenadines', 'en' => 'Saint Vincent and the Grenadines']), 'code' => 'vc'),
            array('id' => '217', 'name' => json_encode( ['ar' => 'فنزويلا', 'fr' => 'Venezuela', 'en' => 'Venezuela']), 'code' => 've'),
            array('id' => '218', 'name' => json_encode( ['ar' => 'جزر العذراء البريطانية)', 'fr' => 'Îles vierges britanniques', 'en' => 'Virgin Islands (British)']), 'code' => 'vg'),
            array('id' => '219', 'name' => json_encode( ['ar' => 'جزر فيرجن (الولايات المتحدة)', 'fr' => 'Îles Vierges (États-Unis)', 'en' => 'Virgin Islands (U.S.)']), 'code' => 'vi'),
            array('id' => '220', 'name' => json_encode( ['ar' => 'فيتنام', 'fr' => 'Viet Nam', 'en' => 'Viet Nam']), 'code' => 'vn'),
            array('id' => '221', 'name' => json_encode( ['ar' => 'فانواتو', 'fr' => 'Vanuatu', 'en' => 'Vanuatu']), 'code' => 'vu'),
            array('id' => '222', 'name' => json_encode( ['ar' => 'واليس وفوتونا', 'fr' => 'Wallis et Futuna', 'en' => 'Wallis and Futuna']), 'code' => 'wf'),
            array('id' => '223', 'name' => json_encode( ['ar' => 'ساموا', 'fr' => 'Samoa', 'en' => 'Samoa']), 'code' => 'ws'),
            array('id' => '224', 'name' => json_encode( ['ar' => 'اليمن', 'fr' => 'Yémen', 'en' => 'Yemen']), 'code' => 'ye'),
            array('id' => '225', 'name' => json_encode( ['ar' => 'مايوت', 'fr' => 'Mayotte', 'en' => 'Mayotte']), 'code' => 'yt'),
            array('id' => '226', 'name' => json_encode( ['ar' => 'جنوب أفريقيا', 'fr' => 'Afrique du Sud', 'en' => 'South Africa']), 'code' => 'za'),
            array('id' => '227', 'name' => json_encode( ['ar' => 'زامبيا', 'fr' => 'Zambie', 'en' => 'Zambia']), 'code' => 'zm'),
            array('id' => '228', 'name' => json_encode( ['ar' => 'زائير (سابقة)', 'fr' => 'Zaïre (ancien)', 'en' => 'Zaire (former)']), 'code' => 'zr'),
            array('id' => '229', 'name' => json_encode( ['ar' => 'زيمبابوي', 'fr' => 'Zimbabwe', 'en' => 'Zimbabwe']), 'code' => 'zw'),
            array('id' => '230', 'name' => json_encode( ['ar' => 'الولايات المتحدة', 'fr' => 'les États-Unis d\'Amérique', 'en' => 'United States of America']), 'code' => 'us'),
            array('id' => '231', 'name' => json_encode( ['ar' => 'غير معروف', 'fr' => 'unknown', 'en' => 'unknown']), 'code' => 'null')
        ];



        DB::table('countries')->insert($countries);


    }
}